-- 1. Users 테이블 (회원 기본 정보)
CREATE TABLE IF NOT EXISTS users (
    id            BIGSERIAL PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password      VARCHAR(255),
    nickname      VARCHAR(50) NOT NULL,
    profile_image VARCHAR(500),
    role          VARCHAR(20) DEFAULT 'USER',
    status        VARCHAR(20) DEFAULT 'ACTIVE',
    is_verified   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Users 테이블 및 컬럼 주석
COMMENT ON TABLE users IS '회원 기본 정보';
COMMENT ON COLUMN users.email IS '로그인 ID 역할';
COMMENT ON COLUMN users.password IS '비밀번호 (소셜 로그인 유저는 NULL)';
COMMENT ON COLUMN users.nickname IS '사용자 닉네임';
COMMENT ON COLUMN users.profile_image IS '프로필 이미지 URL';
COMMENT ON COLUMN users.role IS '권한 (USER, ADMIN)';
COMMENT ON COLUMN users.status IS '상태 (ACTIVE, BANNED, WITHDRAWN)';
COMMENT ON COLUMN users.is_verified IS '이메일 인증 여부';


-- 2. Social Accounts 테이블 (소셜 연동 정보)
CREATE TABLE IF NOT EXISTS social_accounts (
    id            BIGSERIAL PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    provider      VARCHAR(20) NOT NULL,
    provider_id   VARCHAR(255) NOT NULL,
    connected_at  TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_social_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_social_provider UNIQUE (provider, provider_id)
);

-- Social Accounts 테이블 및 컬럼 주석
COMMENT ON TABLE social_accounts IS '소셜 로그인 연동 정보';
COMMENT ON COLUMN social_accounts.provider IS '소셜 제공자 (예: google, kakao, naver)';
COMMENT ON COLUMN social_accounts.provider_id IS '소셜 서비스의 고유 식별값 (sub, id 등)';
COMMENT ON COLUMN social_accounts.connected_at IS '연동된 일시';


-- 3. API Keys 테이블 (API 인증 키 관리)
CREATE TABLE IF NOT EXISTS api_keys (
    id            BIGSERIAL PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    name          VARCHAR(50) NOT NULL,
    access_key    VARCHAR(64) UNIQUE,
    secret_key    VARCHAR(255) UNIQUE,
    is_active     BOOLEAN DEFAULT TRUE,
    last_used_at  TIMESTAMPTZ,
    expires_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_apikey_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- API Keys 테이블 및 컬럼 주석
COMMENT ON TABLE api_keys IS '사용자 API 접근 키 관리';
COMMENT ON COLUMN api_keys.name IS '사용자가 키를 구분하기 위한 별칭 (예: Trading Bot 1)';
COMMENT ON COLUMN api_keys.access_key IS '공개 식별자 (API 호출 시 Header에 포함)';
COMMENT ON COLUMN api_keys.secret_key IS '비밀 키';
COMMENT ON COLUMN api_keys.is_active IS '키 활성화 여부';
COMMENT ON COLUMN api_keys.last_used_at IS '마지막 사용 시점 (보안 감사용)';
COMMENT ON COLUMN api_keys.expires_at IS '키 만료일 (NULL이면 무제한)';

CREATE TABLE IF NOT EXISTS MARKET_CODE (
    id BIGSERIAL PRIMARY KEY,
    market VARCHAR(20) NOT NULL,
    korean_name VARCHAR(20) ,
    english_name VARCHAR(20) ,
    market_warning VARCHAR(20) ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE MARKET_CODE IS '마켓 코드';
COMMENT ON COLUMN MARKET_CODE.market IS '시장 정보';
COMMENT ON COLUMN MARKET_CODE.korean_name IS '한글명';
COMMENT ON COLUMN MARKET_CODE.english_name IS '영문명';
COMMENT ON COLUMN MARKET_CODE.market_warning IS '유의 종목 여부';

-- 4. Spring Batch 메타데이터 테이블
CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE  (
    JOB_INSTANCE_ID BIGINT PRIMARY KEY ,
    VERSION BIGINT ,
    JOB_NAME VARCHAR(100) NOT NULL ,
    JOB_KEY VARCHAR(32) NOT NULL,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION  (
    JOB_EXECUTION_ID BIGINT PRIMARY KEY ,
    VERSION BIGINT  ,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL ,
    END_TIME TIMESTAMP DEFAULT NULL ,
    STATUS VARCHAR(10) ,
    EXIT_CODE VARCHAR(2500) ,
    EXIT_MESSAGE VARCHAR(2500) ,
    LAST_UPDATED TIMESTAMP,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
    references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS  (
    JOB_EXECUTION_ID BIGINT NOT NULL ,
    PARAMETER_NAME VARCHAR(100) NOT NULL ,
    PARAMETER_TYPE VARCHAR(100) NOT NULL ,
    PARAMETER_VALUE VARCHAR(2500) ,
    IDENTIFYING CHAR(1) NOT NULL ,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION  (
    STEP_EXECUTION_ID BIGINT PRIMARY KEY ,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP DEFAULT NULL ,
    END_TIME TIMESTAMP DEFAULT NULL ,
    STATUS VARCHAR(10) ,
    COMMIT_COUNT BIGINT ,
    READ_COUNT BIGINT ,
    FILTER_COUNT BIGINT ,
    WRITE_COUNT BIGINT ,
    READ_SKIP_COUNT BIGINT ,
    WRITE_SKIP_COUNT BIGINT ,
    PROCESS_SKIP_COUNT BIGINT ,
    ROLLBACK_COUNT BIGINT ,
    EXIT_CODE VARCHAR(2500) ,
    EXIT_MESSAGE VARCHAR(2500) ,
    LAST_UPDATED TIMESTAMP,
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT  (
    STEP_EXECUTION_ID BIGINT PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT ,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
    references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT  (
    JOB_EXECUTION_ID BIGINT PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT ,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
    references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_SEQ START WITH 0 MINVALUE 0 MAXVALUE 9223372036854775807 NO CYCLE;

